name: Build Motorola EDGE S (MYUI A12)

on:
  workflow_call:
  workflow_dispatch:

env:
  # ==========================================
  # 核心配置 (Device Info)
  # ==========================================
  DEVICE_NAME: "Motorola_edge_s"
  DEVICE_CODENAME: "nio"
  ROM_TEXT: "myui_a12"

  # ==========================================
  # 编译工具链与内核源
  # ==========================================
  KERNEL_SOURCE: "https://github.com/LineageOS/android_kernel_motorola_sm8250.git"
  KERNEL_BRANCH: "lineage-23.2"

  CLANG_SOURCE: "https://github.com/bachnxuan/aosp_clang_mirror/releases/download/clang-r574158-14475230/clang-r574158.tar.gz"
  CLANG_BRANCH: ""

  CUSTOM_CMDS: "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS: "cc=clang DTC_EXT=/usr/bin/dtc"

  GCC_GNU: false
  GCC_64_SOURCE: "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git"
  GCC_64_BRANCH: "android12L-release"
  GCC_32_SOURCE: "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9.git"
  GCC_32_BRANCH: "android12L-release"

  # ==========================================
  # 内核配置与特性 (Configs & Features)
  # ==========================================
  DEFCONFIG_NAME: "vendor/kona-perf_defconfig"
  DEFCONFIG_FROM_BOOT: false
  BUILD_OTHER_CONFIG: "true"
  MERGE_CONFIG_FILES: "vendor/ext_config/moto-kona.config,vendor/ext_config/nio-default.config"

  KERNELSU_AUTO_GET: "true"
  KERNELSU_AUTO_FORK: "xxksu"
  KERNELSU_METHOD: "shell"

  SUSFS_ENABLE: false
  REKERNEL_ENABLE: "false"
  DROIDSPACES_ENABLE: "false"
  BASEBAND_GUARD_ENABLE: "false"
  KPM_ENABLE: "false"

  # ==========================================
  # 打包与构建工具配置
  # ==========================================
  PACK_METHOD: "Anykernel3"
  AK3_SOURCE: "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH: "master"
  PYTHON_VERSION: "3"

jobs:
  build-kernel:
    name: Motorola edge s (myui A12)
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v6

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get necessary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patching Phase
        run: |
          # 暂时为空

      - name: 🪛 Extra Kernel Options
        run: |
          sudo apt-get install -y device-tree-compiler

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files